### ISSUE TITLE
Importer fails on ValidationError

### ISSUE THREAD

**Issue by peterdewinter** [luckymarmot/Paw-SwaggerImporter#20] opened 2016-04-18 11:30 UTC
Hi,

I'm getting current error when trying to import a swagger defintion.

```
JS Exception Line 11507. Error: Invalid Swagger File (invalid schema / version < 2.0):
ValidationError: String does not match pattern: ^[^{}/ :\\]+(?::\d+)?$
```

I checked the following:
- version is 2.0
- Swagger-ui works.

Small excerpt:

```
{
  "swagger" : "2.0",
  "info" : {
    "title" : "Endpoints documentation",
    "license" : {
      "name" : "Apache 2.0 License",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
...
```

**Comment by mittsh** [comment] 2016-04-18 11:47
@Mijathi Can you make sure you're running the latest Swagger importer? Please go to the Paw menu > Extensions > Check for Extensions Updates.
Saying this because this bug reminds me one we had in a previous version of our Swagger importer, the new one seems to be working fine. Thanks!

**Comment by JonathanMontane** [comment] 2016-08-04 14:45
No news since Apr 18. Closing.

**Closed as completed by JonathanMontane** 2016-08-04 14:45 UTC

**Comment by drewish** [comment] 2017-03-23 20:25
Also running into this. Let me know what you'd need to replicate it.

**Comment by JonathanMontane** [comment] 2017-03-23 20:33
@drewish if you can send the file that fails to be imported to support, it would help us a lot in investigating this issue.

**Note** If you have this exact same error (with the same `ValidationError: String does not match pattern: ^[^{}/ :\\]+(?::\d+)?$`), this might be due to an invalid `host` field value. (this error looks a lot like a failure to match this [pattern](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L30)

In swagger 2.0, per the spec, the `host` field should only contain the `host` section of a URI, which means that `https://whatever.com:429` is not a valid `host` value, but `whatever.com:429` is.

**Comment by drewish** [comment] 2017-03-23 21:27
Here's what I was seeing:
```
JS Exception Line 103205. Error: Invalid Swagger File (invalid schema / version < 2.0):
ValidationError: String does not match pattern: ^/
```

**Updated:** Wondering if it's because someone stuck the hostname in the base path:
```
  "host" : "localhost:9700",
  "basePath" : "http://localhost:9700",
```

**Comment by JonathanMontane** [comment] 2017-03-23 22:34
@drewish `basePath` is incorrect. Per the swagger spec:
> The base path on which the API is served, which is relative to the host. If it is not included, the API is served directly under the host. The value MUST start with a leading slash (/). The basePath does not support path templating.

e.g. if you are serving your api from `https://my.awesome-api.com/v3`,
you should decompose it this way in your swagger file:

```
{
  ...
  "host": "my.awesome-api.com",
  "basePath": "/v3",
  "schemes": [ "https" ]
  ...
}
```

**Comment by JonathanMontane** [comment] 2017-03-23 22:35
@drewish you can validate your swagger files in the online swagger editor: http://editor.swagger.io/

**Comment by drewish** [comment] 2017-03-24 00:44
Yeah I think the problem is that they definitely had invalid swagger but that the error made it sound like the version was wrong.

**Comment by JonathanMontane** [comment] 2017-03-24 08:39
Yeah the `(invalid schema /` is often ignored in favor of the `version < 2.0)` part. I'll see how we can improve this error message. Thanks for the report
