### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by magobaol** [luckymarmot/Paw-SwaggerImporter#29] opened 2016-09-16 09:32 UTC
I'm trying out the importer, version 2.2.11.
If I try to import this url http://petstore.swagger.io/v2/swagger.json it shows this error message:

![screen shot 2016-09-16 at 11 31 09](https://cloud.githubusercontent.com/assets/1880350/18581485/2446bca0-7c01-11e6-9a98-914c464c99ab.png)

Is there some sort of incompatibility?

**Comment by JonathanMontane** [comment] 2016-09-16 09:34
@magobaol thanks for the report! I'll look into it

**Comment by JonathanMontane** [comment] 2016-09-16 09:39
@magobaol it's weird... I imported the file without any issue whatsoever, by pasting the url and also by pasting the text content.

Would you mind telling me what version of Paw and macOS you are using? It is very likely due to the JS engine provided with Yosemite that is aligned on Safari 7, and therefore lacks many standard functionalities, as it is basically 3-5 years behind the current standards.

This issue is not reproducible in El Capitan/Sierra.

**Comment by magobaol** [comment] 2016-09-16 09:45
Paw 3.0.11
OSX 10.10.5
Safari 9.0.2

**Comment by JonathanMontane** [comment] 2016-09-16 09:47
Yup, that's it! Yosemite strikes again ;) I'll try to push a fix for this asap. Sorry for the inconvenience.

**Comment by magobaol** [comment] 2016-09-16 09:56
:-) Waiting for it, thanks!

**Comment by JonathanMontane** [comment] 2016-09-16 13:22
@magobaol I've made some tentative changes to quite a few importers and generators so that they support Yosemite. However, I don't have a machine with Yosemite to test the changes, would it be possible for you to try out a development version?

The following instructions should update your local version of the Swagger Importer

```
git clone https://github.com/luckymarmot/API-Flow.git
cd API-Flow
git checkout 077-yosemite-support-redux
make configure
make transfer TARGET="swagger"
```

Can you check if everything works for you with that version? Thank you for the help!

**Comment by magobaol** [comment] 2016-09-16 13:42
@JonathanMontane last command should install new version directly inside Paw, right?
In this case, the patch isn't working, I get the same error :-(

**Comment by JonathanMontane** [comment] 2016-09-16 13:45
@magobaol woops, do a git pull to get the content of the branch. My bad.

**Comment by magobaol** [comment] 2016-09-16 13:53
Nope. Just to be sure: you wrote to use `077-yosemite-support-redux` but I've only found `077-yosemite-support` and I'm using that one. Is it right?

**Comment by magobaol** [comment] 2016-09-16 16:18
@JonathanMontane I've tried to export API in Swagger and in Postman version, and in both cases I got a similar error. Maybe there's something on Paw itself?

**Comment by JonathanMontane** [comment] 2016-09-19 10:00
@magobaol, `077-yosemite-support` is not the correct branch (it shouldn't even be available, it was deleted a while back), the correct one is `077-yosemite-support-redux`. Most of the exporters used the method `String.startsWith`, because, well, it's very useful method, which was apparently not provided in Yosemite. I removed all usage of this method in every exporters and serializers, it should now work (or at least give us an error about another missing function).

Sorry about the delay. I hope we can fix this quickly today!

**Comment by magobaol** [comment] 2016-09-19 14:58
Hi @JonathanMontane,
I got the right branch. I tried the new version and I got a different error:

`The import Extension has started a JavaScript Promise with no pending callback`

**Comment by JonathanMontane** [comment] 2016-09-20 12:08
@magobaol I've been trying to find which part of the code could potentially cause this issue, to no avail. Is there any additional messages printed in the extensions console (⌘⌥3)?

**Comment by magobaol** [comment] 2016-09-20 13:02
@JonathanMontane this is the error message in the extesion console:

`Error Importer com.luckymarmot.PawExtensions.SwaggerImporter has returned a JavaScript Promise but has no pending callback. Check that your asynchronous JavaScript code is not missing callbacks. A frequent error is to forget calling resolve() or reject() in a Promise implementation.`

**Comment by JonathanMontane** [comment] 2016-09-20 14:34
@magobaol thanks for the help, we're installing yosemite on a machine to see if we can reproduce it. I'll give you more when we're done.

**Comment by JonathanMontane** [comment] 2016-09-21 13:43
@magobaol Finally pinned the issue down!

It has to do with how the MacOS native JS Engine deals with promises (hint: it does not like them). Our current implementation uses webpack and babel to write code that is readable and easier to maintain, which is then transpiled to legacy es5 javascript, for compatibilty reasons. There are a lot of shims, so that the experience is relatively identical on every machine, etc and overall, it works really well. Not this time, however. The issue you had comes from a little generated function that deals with shimming promises. It starts by checking if all the cool stuff is there (Is it Node.js? Does it support the Observable pattern? etc.) until it gets to the most basic features. The issue is that it is too trusting! Apparently the JS Engine implementation of Promises is only half done in yosemite (and full of bug), such that a Promise that resolves immediately never calls its handlers. So the shimming function checks for the existence of a Promise, and of a few of the associated methods, and uses them (except that they don't work correctly).

I've found a way to fix this, although it is lackluster, and I'm looking for a better way to solve this issue.
If you want to fix this issue, open the extension manager, and click on the swagger importer, and then click on open directory.

![image](https://cloud.githubusercontent.com/assets/5136989/18713025/2c6d3ce2-8011-11e6-89d5-4623ea2017f1.png)

![image](https://cloud.githubusercontent.com/assets/5136989/18713071/54902bf8-8011-11e6-899c-93ec04f995e7.png)

Open the `SwaggerImporter.js` file with a text editor, and navigate to function number 125 (you can find it by searching for `/* 125 */`).

![image](https://cloud.githubusercontent.com/assets/5136989/18713175/a489c45c-8011-11e6-97a7-2528c4f561b1.png)

Now, **Delete the highlighted lines**. Your file should look like this now:

![image](https://cloud.githubusercontent.com/assets/5136989/18713227/d1739998-8011-11e6-986b-5b1fdc37a520.png)

And that should do it!

This is not at all satisfactory, and it will break every time the extension is updated, but I thought you could find it useful if you were to encounter this error again.

I'll keep looking for a better solution in any case.

**Comment by JonathanMontane** [comment] 2016-09-21 14:14
@magobaol We've found a way to fix this issue permanently on Yosemite. It'll come out with the next version of Paw (ETA: 1day). So you can use this fix in the meantime!

**Comment by magobaol** [comment] 2016-09-22 07:58
Hi @JonathanMontane, sorry for the delay, I was on a business trip yesterday.
This morning, Paw downloaded an updated version of the importer, but I got the same problem. Btw, I think I have to wait for the next version of Paw itself, as you said.

Thanks,
Francesco

**Comment by magobaol** [comment] 2016-09-22 14:22
@JonathanMontane everything works with Paw 3.0.2! Thanks for all the effort you put in this!

**Closed as completed** 2016-09-24 14:18 UTC
Labels: OS:Yosemite
